---
  root: true
  parser: babel-eslint
  env:
    browser: true
  plugins:
    - react
  extends:
    - airbnb-base
    - plugin:react/recommended
  rules:
    import/no-extraneous-dependencies: 0
    global-require: 0

